### ISSUE TITLE
Screenshots should be replaced

### ISSUE THREAD

**Issue by kfl** [madsobitsoe/CATITOR#1]
The screenshots should be replaced with an [asciinema recording](https://asciinema.org/).

Three screen shots right after each other is confusing.

**Comment by madsobitsoe** [comment]
I find this to be a very valid point that will hopefully lessen the learning curve of switching to the non-standard UNIX editor. 

Commit 064bf5ed062008879e24bf1bcf52a67f1a60272c should solve this issue.

Thank you!
