### ISSUE TITLE
Missing benchmarks

### ISSUE THREAD

**Issue by kfl** [madsobitsoe/CATITOR#2]
What is the performance like wrt the standard editor `ed`?

**Comment by madsobitsoe** [comment]
I would love to add benchmarks, but they will be hard or impossible to conduct seeing as CATITOR doesn't support the full feature-set of the standard editor `ed`. 

I'll have to pick my brain for this one. It might be possible to construct a comparison-matrix and even include abonimations like vscode, but a number-heavy proper benchmark seems out of reach.

**Comment by madsobitsoe** [comment]
Commit 60e772c209640a25f10ee99696f497c491927765 added a comparison matrix. 
Does this solve the issue with missing banchmarks for you or do you have a more specific request?

**Comment by kfl** [comment]
The feature matrix gives a great overview. 

I'm mostly interested in the "Adding Lines" feature and would have liked to see a performance comparison with `ed`, to determine if CATITOR could replace `ed` in [scripts](https://wiki.bash-hackers.org/howto/edit-ed).

I'll close the issue for now, but might reopen it when CATITOR grows the "Adding Lines" feature.
